### ISSUE TITLE
The app.md states:

### ISSUE THREAD

**Issue by recursos** [leoz0214/StreetViewImageDownloader#2]
The app.md states:
A pre-built standalone **Windows EXE** is available in a Release, which can be downloaded and run directly.

But I can´t find it.
Has it been removed?

**Comment by recursos** [comment]
At last I noticed package_release.py.
But running it:

Traceback (most recent call last):
  File "D:\SVIDownloader-main\package_release.py", line 83, in <module>
    main()
  File "D:\SVIDownloader-main\package_release.py", line 79, in main
    package_exe()
  File "D:\SVIDownloader-main\package_release.py", line 67, in package_exe
    subprocess.run(command_parts)
  File "C:\Users\ruias\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ruias\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\ruias\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

Could you help?

**Comment by recursos** [comment]
searching, found advice to:
pip install pyinstaller
which I did, but to no avail

**Comment by recursos** [comment]
Next I installed:
pip install aiohttp requests pillow psutil pyglet

and tried again
py package_release.py
but still same error

**Comment by recursos** [comment]
Next I tried:
"D:\SVIDownloader-main\src\gui>py main.py

Ths main windows opens nicely, but then:

Warning: Rendering not possible as required C++ object file not found.
Warning: Foreground window check not possible as required C++ object file not found. Capture by keybind no longer works for live downloading."

What could be the "C++object file" ??

**Comment by recursos** [comment]
Later I noticed that in:

**Comment by recursos** [comment]
\StreetViewImageDownloader-main\src\gui\cpp

there were:
projection.cpp
conversion.h
cubemap.cpp
foreground.cpp

So I installed  msys64 to have g++ and compiled according to APP.md:

"note that `conversion.so` is a shared library formed by compiling `cubemap.cpp` and `projection.cpp` and `foreground.so` is a shared library by compiling `foreground.cpp`. For example, for `conversion.so`, the following g++ command has been used with `src/gui/cpp` as the current working directory: `g++ cubemap.cpp projection.cpp --static --shared -o conversion.so -O2`"

and got the `.so files

Anyway, running
package_release.py
or
run_app.py
gave me xactly the same error above.

**Comment by recursos** [comment]
And as a last effort I used VSCode to debug (single step) into subprocess().
The traceback says:

` File "C:\Users\ruias\AppData\Local\Programs\Python\Python312\Lib\site-packages\debugpy\_vendored\pydevd\_pydev_bundle\pydev_monkey.py", line 901, in new_CreateProcess
    return getattr(_subprocess, original_name)(app_name, cmd_line, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified`

but I can't understand this.
And I am stuck!
